// <auto-generated />
namespace PhoneRegister.DataModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class idNum2String : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idNum2String));
        
        string IMigrationMetadata.Id
        {
            get { return "201811061259488_idNum2String"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
